<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class productsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            [ 
                "id" => 5,
                "category_id" => 3,
                "title" => "Round Reading Glass For Men & Women",
                "slug" => "Round Reading Glass For Men & Women",
                "brand" => 1,
                "model" => "Round Reading Glass For Men & Women",
                "image" => "1675232167.jpg",
                "short_desc" => NULL,
                "desc" => NULL,
                "keywords" => NULL,
                "technical_specification" => NULL,
                "uses" => NULL,
                "warranty" => NULL,
                "tax_id" => 2,
                "is_promo" => 1,
                "is_featured" => 1,
                "is_discounted" => 1,
                "is_tranding" => 1,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
            [ 
                "id" => 6,
                "category_id" => 3,
                "title" => "Women Printed Round Neck Black T-Shirt",
                "slug" => "Women Printed Round Neck Black T-Shirt",
                "brand" => 1,
                "model" => "Women Printed Round Neck Black T-Shirt",
                "image" => "1675232280.jpg",
                "short_desc" => "<ul><li>Care Instructions: <strong>Machine Wash</strong></li><li>Fit Type: Regular Fit</li><li>Occasion : <strong>Leisure Sport</strong></li><li>Pattern : Solid</li><li>Fit :Regular Fit</li><li>Material: <strong>60% Cotton, 40% Polyester</strong></li><li>Sleeves : Half Sleeves</li></ul>",
                "desc" => "<blockquote><ul><li>Care Instructions: <strong>Machine Wash</strong></li><li>Fabric Composition : <strong>100% Cotton</strong></li><li>Premium Super Combed Cotton Jersey Fabric Is Soft &amp; Comfortable For All Day Wear Due To Its Good <strong>Absorbency &amp; Breathability</strong></li><li>Half Sleeves</li><li>Closure Type: Pull On;<strong> Collar Style: Collarless</strong></li></ul></blockquote>",
                "keywords" => "tshirt",
                "technical_specification" => "Youth fit unisex Durable fabrics 4.5 oz or 153 g Material: 100% combed ring-spun cotton Exception: heather colour (90% combed ring-spun cotton / 10% polyester) Exception: heather colour (90% combed ring-spun cotton / 10% polyester) Ribbed collar to ensure the shape of the neckline Shoulder to shoulder self-fabric binding to secure shape and avoid stretch, sag or break Side-seamed for a more tailored and flattering fit Double needle sleeves and bottom hem for a cleaner finish and more durable look Direct to garment printing using water based ink for an eco friendly result We work with fair and responsible apparel suppliers that use sustainably sourced cotton",
                "uses" => "T-shirts were originally worn as undershirts, but are now worn frequently as the only piece of clothing on the top half of the body, other than possibly a brassiere or, rarely, a waistcoat (vest). T-shirts have also become a medium for self-expression and advertising, with any imaginable combination of words, art and photographs on display.",
                "warranty" => "15 Day Repacement warranty",
                "tax_id" => 2,
                "is_promo" => 0,
                "is_featured" => 1,
                "is_discounted" => 0,
                "is_tranding" => 0,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
            [ 
                "id" => 7,
                "category_id" => 4,
                "title" => "teddy bear pink colors size 3 feet very soft teddy bear",
                "slug" => "teddy bear pink colors size 3 feet very soft teddy bear",
                "brand" => 1,
                "model" => "1234",
                "image" => "1675232452.jpg",
                "short_desc" => NULL,
                "desc" => NULL,
                "keywords" => NULL,
                "technical_specification" => NULL,
                "uses" => NULL,
                "warranty" => "15 Day Repacement warranty",
                "tax_id" => 2,
                "is_promo" => 0,
                "is_featured" => 0,
                "is_discounted" => 0,
                "is_tranding" => 1,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
            [ 
                "id" => 8,
                "category_id" => 3,
                "title" => "Men Graphic Print Round Neck Black T-Shirt",
                "slug" => "Men Graphic Print Round Neck Black T-Shirt",
                "brand" => 1,
                "model" => "Men Graphic Print Round Neck Black T-Shirt",
                "image" => "1675232958.jpg",
                "short_desc" => NULL,
                "desc" => NULL,
                "keywords" => NULL,
                "technical_specification" => NULL,
                "uses" => NULL,
                "warranty" => NULL,
                "tax_id" => 2,
                "is_promo" => 0,
                "is_featured" => 0,
                "is_discounted" => 0,
                "is_tranding" => 1,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
            [ 
                "id" => 26,
                "category_id" => 3,
                "title" => "t-shirts2",
                "slug" => "t-shirts2",
                "brand" => 1,
                "model" => "t-shirts2",
                "image" => "1675669792.jpg",
                "short_desc" => NULL,
                "desc" => NULL,
                "keywords" => NULL,
                "technical_specification" => NULL,
                "uses" => NULL,
                "warranty" => NULL,
                "tax_id" => 0,
                "is_promo" => 0,
                "is_featured" => 0,
                "is_discounted" => 0,
                "is_tranding" => 0,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
            [ 
                "id" => 27,
                "category_id" => 4,
                "title" => "Tshirt",
                "slug" => "Tshirt",
                "brand" => 1,
                "model" => "Tshirt",
                "image" => "1675734113.jpg",
                "short_desc" => NULL,
                "desc" => NULL,
                "keywords" => NULL,
                "technical_specification" => NULL,
                "uses" => NULL,
                "warranty" => NULL,
                "tax_id" => 1,
                "is_promo" => 0,
                "is_featured" => 0,
                "is_discounted" => 0,
                "is_tranding" => 0,
                "product_status" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ],
        ];
        DB::table("products")
        ->insert($data);
    }
}
